tap "homebrew/services"
tap "oven-sh/bun"

brew "awscli"
brew "bat"
brew "colima", restart_service: true
brew "docker"
brew "docker-compose"
brew "eza"
brew "fish"
brew "git"
brew "git-delta"
brew "htop"
brew "jq"
brew "lazydocker"
brew "neovim"
brew "pyenv"
brew "starship"
brew "ripgrep"
brew "fd"
brew "git-crypt"

cask "1password"
cask "alt-tab"
cask "arc"
cask "firefox"
cask "font-jetbrains-mono-nerd-font"
cask "hiddenbar"
cask "linearmouse"
cask "postico"
cask "raycast"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "wezterm"
cask "google-cloud-sdk"
